### ISSUE TITLE
Feature Request:  Export as SVG/PNG

### ISSUE THREAD

**Issue by Marcus-James-Adams** [pcasteran/terraform-graph-beautifier#8]
If the graph beautifier had the ability to export directly to svg/png format files,
these could be embedded into our terrform repos readme.md

**Comment by pcasteran** [comment]
@Marcus-James-Adams I'm sorry for taking so long to answer you, I did not had time to work on this project lately.

The tool has been designed in the Unix command line philosophy to be integrated in a command pipeline, combining several minimal tools to achieve the expected behavior. This means that, by default, it reads the graph to process from the standard input (`stdin`) and produces the cleaned version on the standard output (`stdout`).

In that spirit, in order to keep the tool as minimal as possible, I would rather not add exports that already can be achieved otherwise. To generate a SVG or PNG from the output of the tool you could use the [`dot`](https://graphviz.org/doc/info/command.html#-T) command, available when [installing Graphviz](https://graphviz.org/download/). For example:

```bash

# SVG
terraform graph | terraform-graph-beautifier --output-type=graphviz | dot -Tpng:cairo:cairo > config.png

# PNG
terraform graph | terraform-graph-beautifier --output-type=graphviz | dot -Tsvg:cairo:cairo > config.svg
```

**Comment by pcasteran** [comment]
I'm closing this issue as there has been no feedback on the proposed solution.
